In [6]:
import numpy #para usar biblioteca
#import numpy as np --> posso referenciar o numpy apenas pelo np

In [5]:
a = numpy.array([10,20,30,40,50]) #array pega uma lista e converte em array
a

array([10, 20, 30, 40, 50])

In [7]:
type(a)

numpy.ndarray

In [9]:
matris = numpy.array([[1,2],[3,4]])
matris

array([[1, 2],
       [3, 4]])

In [10]:
type(matris)

numpy.ndarray

In [13]:
print(matris[1][1])
print(matris[-1][-1]) # as duas formas imprimem ultimo valor, matris 2x2

4
4


In [16]:
matris[1,:] #todas os dados da primeira linha 

array([3, 4])

In [19]:
matris[:,0] #primeira coluna 

array([1, 3])

In [21]:
matris.transpose() #matris transposta

array([[1, 3],
       [2, 4]])

In [22]:
mat1 = numpy.array([[10,20],[30,40]])
mat2 = numpy.array([[15,25],[35,45]])
mat1 + mat2

array([[-5, -5],
       [-5, -5]])

In [26]:
mat1 - mat2

array([[-5, -5],
       [-5, -5]])

In [28]:
mat1 * mat2

array([[ 150,  500],
       [1050, 1800]])

In [30]:
m3 = numpy.array([1,2,3,4])
m3.sum()

10

In [35]:
m3.argmax() #indice

3

In [18]:
jack = numpy.array([1, 2, 123, 10])
ja = numpy.array([3, 4, 123, 10])
jack*ja

array([    3,     8, 15129,   100])