In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [16]:
np.insert(arr, 0, 10)

array([10,  1,  2,  3])

In [19]:
a= np.array([[1,2],[3,4]])
print(a)
print(a.ndim) # quantidade de eixos

[[1 2]
 [3 4]]
2


In [21]:
print(a.sum(axis=0))

[4 6]


In [23]:
print(a.sum(axis=1))

[3 7]


In [26]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 2],
       [3, 5, 4]])

In [28]:
np.insert(a, 0, 5, axis=0)

array([[5, 5],
       [1, 2],
       [3, 4]])

In [30]:
#append
b = np.array([1,2,3])
b

array([1, 2, 3])

In [34]:
np.append(b,[4,5,6])

array([1, 2, 3, 4, 5, 6])

In [39]:
c= np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [46]:
np.append(c, [[5,6]])

array([1, 2, 3, 4, 5, 6])

In [56]:
np.append(c, [[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
c.ndim

2

In [67]:
e= np.array([[1,2],[3,4], [5,6]])
np.delete(e, 1, axis= 0)

array([[1, 2],
       [5, 6]])

In [69]:
np.delete(e, 0, axis = 1)

array([[2],
       [4],
       [6]])

In [71]:
np.delete(e, np.s_[::2], 0) 

array([[3, 4]])

In [74]:
#repetir elementos
e= np.array([[1,2],[3,4]])
np.repeat(e,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [76]:
np.repeat(e, 2, axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [78]:
np.repeat(e, 2, axis = 1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [82]:
#repitir no mesmo eixo, não se usa 'axis'
e= np.array([[1,2],[3,4]])
e

array([[1, 2],
       [3, 4]])

In [84]:
np.tile(e,2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [86]:
#dividir array
e= np.array([[1,2,3],[4,5,6]])

In [88]:
np.array_split(e, 2, axis = 0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [91]:
np.array_split(e, 3, axis = 1)

[array([[1],
        [4]]), array([[2],
        [5]]), array([[3],
        [6]])]

In [94]:
#arrays de 0 e 1
np.zeros(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [98]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [100]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [103]:
e = np.eye(5)
e

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [105]:
#logicas com matris
e= np.array([[1,2,3],[4,5,6]])
e[e>2]

array([3, 4, 5, 6])

In [107]:
ex = (e>2)
ex

array([[False, False,  True],
       [ True,  True,  True]], dtype=bool)