In [37]:
import numpy as np
from pybrain.datasets import SupervisedDataSet
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised import BackpropTrainer

In [38]:
entradas = np.genfromtxt('../Dados/iris2.data', delimiter=',', usecols=(0,1,2,3))
saidas = np.genfromtxt('../Dados/iris2.data', delimiter=',', usecols=(4))
print(len(entradas))
print(len(saidas))

150
150


In [39]:
'''
Iris-setosa: 0
Iris-versicolor: 1
Iris-virginica: 2
'''

print(entradas[:5])
print(saidas[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0. 0. 0. 0. 0.]


In [40]:
#uso de 70% da amostragem para treino
entradas_treino = np.concatenate((entradas[0:35], entradas[50:85], entradas[100:135]))
saidas_treino = np.concatenate((saidas[0:35], saidas[50:85], saidas[100:135]))

In [41]:
#Uso de 30% para teste
entradas_teste = np.concatenate((entradas[35:50], entradas[85:100], entradas[135:]))
saidas_teste = np.concatenate((saidas[35:50], saidas[85:100], saidas[135:]))

In [42]:
treinar = SupervisedDataSet(4,1)
for i in range(len(entradas_treino)):
    treinar.addSample(entradas_treino[i], saidas_treino[i])
print(len(treinar))
print(treinar.indim)
print(treinar.outdim)
    

105
4
1


In [43]:
#construindo rede
rede = buildNetwork(treinar.indim, 2, treinar.outdim, bias=True)
treino = BackpropTrainer(rede, treinar, learningrate=0.01, momentum=0.3)

#trenar rede
for epoca in range(1000):
    treino.train()
    
#testando rede
teste = SupervisedDataSet(4,1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i],saidas_teste[i])
treino.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[-0.004]')
('correct:', '[0     ]')
error:  0.00000867
('out:    ', '[-0.011]')
('correct:', '[0     ]')
error:  0.00005846
('out:    ', '[-0    ]')
('correct:', '[0     ]')
error:  0.00000001
('out:    ', '[0.007 ]')
('correct:', '[0     ]')
error:  0.00002574
('out:    ', '[-0.005]')
('correct:', '[0     ]')
error:  0.00001173
('out:    ', '[-0.006]')
('correct:', '[0     ]')
error:  0.00001750
('out:    ', '[0.043 ]')
('correct:', '[0     ]')
error:  0.00093821
('out:    ', '[0.002 ]')
('correct:', '[0     ]')
error:  0.00000143
('out:    ', '[0.011 ]')
('correct:', '[0     ]')
error:  0.00006017
('out:    ', '[0     ]')
('correct:', '[0     ]')
error:  0.00000000
('out:    ', '[0.01  ]')
('correct:', '[0     ]')
error:  0.00004736
('out:    ', '[-0.01 ]')
('correct:', '[0     ]')
error:  0.00005207
('out:    ', '[0.002 ]')
('correct:', '[0     ]')
error:  0.00000149
('out:    ', '[-0.011]')
('correct:', '[0     ]')
error:  0.00005844
('out:    ', '[-

0.018575443498214415

In [44]:
#construindo rede
#alterando momentum, learnigrate e ciclos de epoca
rede = buildNetwork(treinar.indim, 2, treinar.outdim, bias=True)
treino = BackpropTrainer(rede, treinar, learningrate=0.005, momentum=0.5)

#trenar rede
for epoca in range(2000):
    treino.train()
    
#testando rede
teste = SupervisedDataSet(4,1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i],saidas_teste[i])
treino.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.007 ]')
('correct:', '[0     ]')
error:  0.00002173
('out:    ', '[-0    ]')
('correct:', '[0     ]')
error:  0.00000003
('out:    ', '[0.013 ]')
('correct:', '[0     ]')
error:  0.00008414
('out:    ', '[0.02  ]')
('correct:', '[0     ]')
error:  0.00020239
('out:    ', '[0.008 ]')
('correct:', '[0     ]')
error:  0.00003038
('out:    ', '[0.006 ]')
('correct:', '[0     ]')
error:  0.00001599
('out:    ', '[0.06  ]')
('correct:', '[0     ]')
error:  0.00182358
('out:    ', '[0.014 ]')
('correct:', '[0     ]')
error:  0.00009792
('out:    ', '[0.028 ]')
('correct:', '[0     ]')
error:  0.00039980
('out:    ', '[0.016 ]')
('correct:', '[0     ]')
error:  0.00012247
('out:    ', '[0.024 ]')
('correct:', '[0     ]')
error:  0.00029574
('out:    ', '[0.002 ]')
('correct:', '[0     ]')
error:  0.00000160
('out:    ', '[0.015 ]')
('correct:', '[0     ]')
error:  0.00010936
('out:    ', '[0.001 ]')
('correct:', '[0     ]')
error:  0.00000025
('out:    ', '[0

0.011589690887911158