# Numpy (Numerical Python)

NumPy (ou Numpy) é uma biblioteca de álgebra linear para Python, a razão pela qual é tão importante para a Data Science com Python é que quase todas as bibliotecas dependem do NumPy como um dos seus principais blocos de construção.

Numpy também é incrivelmente rápido, pois tem ligações para bibliotecas C.


# Vetores, Arrays, ndarray e Random

In [212]:
import numpy as np 

In [213]:
#Converter para Array do NumPy
lista = [1,2,3]
np.array(list)
lista

[1, 2, 3]

In [214]:
matris = [[1,2],[3,4],[5,6],[7,8],[9,12],[11,21]]
np.array(matris)          

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 12],
       [11, 21]])

In [215]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [216]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [217]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [218]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [219]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [220]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [221]:
#coloca valores igualmente espaçados
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [222]:
#Distribuição uniforme, entre 0 e 1
np.random.rand(5)

array([0.38624355, 0.94451024, 0.37350694, 0.77263978, 0.39091411])

In [223]:
np.random.rand(5,4,3)

array([[[0.44460207, 0.29095013, 0.34837224],
        [0.98947784, 0.84518096, 0.11341622],
        [0.18884961, 0.02602609, 0.24312761],
        [0.55795491, 0.85747431, 0.20848725]],

       [[0.67973511, 0.32369006, 0.4263338 ],
        [0.56210872, 0.15769215, 0.78537739],
        [0.76888411, 0.81633032, 0.6876858 ],
        [0.20773284, 0.06458493, 0.43473082]],

       [[0.70072434, 0.61612194, 0.61131205],
        [0.30424552, 0.33794531, 0.67000516],
        [0.51064776, 0.21913848, 0.79014891],
        [0.02052427, 0.64172212, 0.41538035]],

       [[0.29869607, 0.88443664, 0.59118789],
        [0.31972983, 0.47522138, 0.34704605],
        [0.22457411, 0.53044838, 0.50241331],
        [0.10427721, 0.09529148, 0.97808808]],

       [[0.24099688, 0.83555473, 0.35501584],
        [0.44413828, 0.4555707 , 0.11812408],
        [0.25083161, 0.03282061, 0.874813  ],
        [0.86468751, 0.44477552, 0.14139838]]])

In [224]:
#distribuição normal, media 0, desvio padrão 1
np.random.randn(5,4)

array([[-1.36674517,  0.30084998,  0.10378423,  0.36491278],
       [ 0.07542263, -1.02760021,  0.4998863 ,  0.48979412],
       [ 0.57096557,  1.64896878, -1.19602271,  0.17334403],
       [ 0.8985394 , -0.91115606, -1.17458419, -2.16223489],
       [ 0.07676756, -1.23109469, -0.23028628,  0.57791141]])

In [225]:
np.random.randint(0,10,10)

array([8, 8, 1, 9, 7, 7, 2, 9, 2, 5])

In [226]:
np.random.randint(5,50,5)

array([39, 35, 12, 28, 21])

In [227]:
np.random.randint(5,40,4)

array([14, 35,  8, 15])

In [228]:
#Converter o .Rand em int
np.random.rand(10) * 100

array([81.88685468, 77.31618674, 69.10300094, 28.37112154, 66.82838964,
       60.28283716, 59.65852286, 37.06099414,  6.23037044,  4.95075748])

In [229]:
#reshape - monta a matris de acordo com os valores
np.random.randint(5,500,50).reshape((5,10))

array([[354, 279, 414,  64, 387, 445, 129, 441, 338, 455],
       [101, 367, 197, 267, 442, 222, 350, 139, 162,  92],
       [194, 383, 374, 296, 395, 334, 398, 491, 490,  85],
       [337, 344,  28, 361,  39, 390, 489, 391, 445,  85],
       [163, 321,  41, 458, 309,  81, 323,  31, 420, 176]])

# Indexação e Fatiamento (slice)


In [230]:
arr = np.arange(0,30,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [231]:
arr[:2]

array([0, 3])

In [232]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [233]:
arr[-3:]

array([21, 24, 27])

In [234]:
arr[::-1]

array([27, 24, 21, 18, 15, 12,  9,  6,  3,  0])

In [235]:
arr[2:] = 100
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [236]:
arr = np.arange(50).reshape((5,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [237]:
arr.shape

(5, 10)

In [238]:
arr[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [239]:
arr[[1],[2]]

array([12])

In [240]:
#valores são apontados para a matris origem
arr2 = arr[:2] = 100
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [241]:
#realiza uma copya ao invez de apontar 
arr2 = arr[:3].copy()
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [242]:
arr2[:] = 30
print(arr)
print('\n')
print(arr2)

[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]]


[[30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]]


### Outras sintaxes de fatiamento

In [243]:
arr[1,4]

100

In [244]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 35,  36,  37,  38,  39]])

### Fancy Indexing
Indexação feita passando um array de inteiros

obs: os dados sempre são copiados para um novo array diferente do slice normal

In [285]:
array_francy = np.empty((8,4))
array_francy

array([[2.29175545e-312, 2.05833592e-312, 2.01589600e-312,
        2.41907520e-312],
       [2.05833592e-312, 6.79038654e-313, 6.79038653e-313,
        2.37663529e-312],
       [2.05833592e-312, 2.41907520e-312, 2.56761491e-312,
        1.93101617e-312],
       [1.06099790e-312, 9.33678148e-313, 9.76118064e-313,
        1.14587773e-312],
       [6.79038653e-313, 1.08221785e-312, 9.33678148e-313,
        9.76118064e-313],
       [1.01855798e-312, 9.33678148e-313, 2.46151512e-312,
        2.37663529e-312],
       [1.29441743e-312, 2.37663529e-312, 2.16443571e-312,
        2.35541533e-312],
       [2.46151512e-312, 1.10343781e-312, 1.03977794e-312,
        1.01855798e-312]])

In [289]:
for i in range(8):
    array_francy[i] = i

In [291]:
array_francy

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [293]:
#pega os valores atravez da seqencia umerica passada
array_francy[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [297]:
array_francy = np.arange(32).reshape((8,4))
array_francy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [299]:
#busca valores correspondentes as listas passadas em linha e coluna
array_francy[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [300]:
array_francy[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Operações Logicas

In [245]:
#retorna uma matirs de valores booleanos
bol = arr > 40
bol

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [246]:
#retorna os valores True da matris
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100,  41,  42,  43,  44,  45,  46,
        47,  48,  49])

In [247]:
array = np.linspace(0,100,30)
array.shape

(30,)

In [248]:
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [249]:
array = array.reshape(3,10)
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [250]:
array[0:2,2]

array([ 6.89655172, 41.37931034])

In [251]:
array[array > 30]

array([ 31.03448276,  34.48275862,  37.93103448,  41.37931034,
        44.82758621,  48.27586207,  51.72413793,  55.17241379,
        58.62068966,  62.06896552,  65.51724138,  68.96551724,
        72.4137931 ,  75.86206897,  79.31034483,  82.75862069,
        86.20689655,  89.65517241,  93.10344828,  96.55172414,
       100.        ])

### Operações com Numpy
##### Vetorização (Vectorization) - termo dado quando se permite expressar operações em lote nos dados sem necessitar a escrita de enlaces.

In [252]:
arr =np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [253]:
arr2 = np.arange(16,32)
arr2

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [254]:
arr + arr2

array([16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46])

In [255]:
arr - arr2

array([-16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16, -16,
       -16, -16, -16])

In [256]:
arr * arr2

array([  0,  17,  36,  57,  80, 105, 132, 161, 192, 225, 260, 297, 336,
       377, 420, 465])

In [257]:
#valores de divisão por zero retornam valores nan
arr / arr2

array([0.        , 0.05882353, 0.11111111, 0.15789474, 0.2       ,
       0.23809524, 0.27272727, 0.30434783, 0.33333333, 0.36      ,
       0.38461538, 0.40740741, 0.42857143, 0.44827586, 0.46666667,
       0.48387097])

In [258]:
1 / arr

c:\users\dogll\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [259]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225], dtype=int32)

In [260]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [261]:
#array de raiz quadrada
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [262]:
#exponenciação
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [263]:
#media
np.mean(arr)

7.5

In [264]:
#seno
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [265]:
np.max(arr)
#ou arr.max() - funcão do objeto arry

15

In [266]:
np.min(arr)
#ou arr.min() - funcão do objeto arry

0

In [267]:
np.empty(shape= (2,8))

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021, -0.53657292,
         0.42016704,  0.99060736,  0.65028784]])

In [268]:
np.full(shape= (2,8), fill_value=10)

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10]])

In [269]:
#Consegue-se guardar funçoes em ndarrays
arr = np.array([np.mean, np.max])

In [270]:
#uso da função mean
arr[1](array)

100.0

### Cast
obs: Chamar astype sempre gera um novo array(copia dos dados), mesmo sendo igual

In [271]:
array.dtype

dtype('float64')

In [272]:
#perde-se o ponto flutuante
array.astype(np.int64)

array([[  0,   3,   6,  10,  13,  17,  20,  24,  27,  31],
       [ 34,  37,  41,  44,  48,  51,  55,  58,  62,  65],
       [ 68,  72,  75,  79,  82,  86,  89,  93,  96, 100]], dtype=int64)

In [273]:
#converte valores Strings numericos apenas 
a= np.array(['1.25','40','3.2','12'])
a.astype(np.float64)

array([ 1.25, 40.  ,  3.2 , 12.  ])

In [274]:
#Atributos dtype de outro objeto tambem podem ser usados
int_array = np.arange(10)
int_array.dtype

dtype('int32')

In [275]:
float_array = np.array([.22, .56, .30, .80],dtype=np.float64)
float_array.dtype

dtype('float64')

In [276]:
float_array.astype(np.int64)
float_array.dtype

dtype('float64')